name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  intl: ^0.20.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  cupertino_icons: ^1.0.8
  provider: 6.1.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  font_awesome_flutter: ^10.8.0
  google_fonts : ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.1
  syncfusion_flutter_charts: ^28.2.6
  syncfusion_flutter_core: ^28.2.6
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Montserrat/Montserrat-Regular.ttf
    - assets/fonts/Montserrat/Montserrat-Light.ttf
    - assets/fonts/Montserrat/Montserrat-Bold.ttf
    - assets/fonts/Montserrat/Montserrat-Italic.ttf
    - assets/fonts/Alkalami/PTSerif-Bold.ttf
    - assets/fonts/Alkalami/PTSerif-BoldItalic.ttf
    - assets/fonts/Alkalami/PTSerif-Italic.ttf
    - assets/fonts/Alkalami/PTSerif-Regular.ttf
    - assets/image/student.png
    - assets/image/logoApple.png
    - assets/image/groupe.png
    - assets/image/googleLogo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
    - family: Alkalami
      fonts:
        - asset: assets/fonts/Alkalami/PTSerif-Bold.ttf
        - asset: assets/fonts/Alkalami/PTSerif-BoldItalic.ttf
        - asset: assets/fonts/Alkalami/PTSerif-Italic.ttf
        - asset: assets/fonts/Alkalami/PTSerif-Regular.ttf

